---
ID: "3bbeaa63-bee4-4f26-8818-aaf564f0b43e"
Parent: "dca88b59-5740-403b-a827-50febbf8afa0"
Template: "c7d9d293-4ef8-4380-8e10-c4632e729f39"
Path: /sitecore/content/Utilities/Home/_Local/Environmental Customer Header
DB: master
SharedFields:
- ID: "e8ab122c-6f54-4d4e-aec6-f81addc558fc"
  Hint: TeaserLink
  Value: |
    <link linktype="internal" text="Read more" querystring="" target="" id="{19855B5A-E7BD-477A-8FB4-8DCDAB4423DC}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0f6b5546-e0ab-4487-81de-640c1aa1b65b"
      Hint: TeaserImage
      Value: |
        <image mediaid="{5897C9CA-855A-4B08-AAEF-FEC107CD0614}" />
    - ID: "13d97a52-7c4e-407c-960d-fadde8a3c1b1"
      Hint: TeaserSummary
      Value: "Rooftops? Panels? Backup power? Habitat makes it easy to switch to solar on all levels. Our dedicated team will handle everything from start to finish. We’ll even assign a solar specialist to your project who will guide you through the process and keep you informed about what’s happening every step of the way."
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161229T095839Z
    - ID: "4a59d072-5b41-4a79-a157-2b2ccac10f2b"
      Hint: TeaserTitle
      Value: Energy independence. Solar products to power your world
