---
ID: "f4062186-0ded-4d7d-b1cf-953e21fa559e"
Parent: "9710c87c-4ebf-466e-bef1-4ec4138209ab"
Template: "8ce2707a-3742-4a89-933b-065e5be02bc9"
Path: /sitecore/system/Marketing Control Panel/Engagement Plans/Finance/Emails/December Finance Newsletter/Productive Visitors
DB: master
SharedFields:
- ID: "07ce07cb-078c-415e-8f92-96690babd6c7"
  Hint: Time interval
  Value: 0
- ID: "3f72bc07-de92-483e-a724-d430769d9ba4"
  Hint: Designer ID
  Value: "24963ae9-1c8c-4e18-8eee-01bc249d1f1b"
- ID: "7642ed71-348b-4b88-8634-cc7b28949472"
  Hint: Origin ID
  Value: "00000000-0000-0000-0000-000000000000"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 700
- ID: "fb8abc73-7acf-45a0-898c-d3ccb889c3ee"
  Hint: Final
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Fields:
  - ID: "06f2d72a-1924-4b9a-ba1e-186ce4e57efd"
    Hint: Description
    Value: These people received the message, clicked on a link, and produced value on the site.
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Productive Visitors
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: "20110401T130032:634372596329665357"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
