---
ID: "a1532a8b-8e2b-4d36-9428-0539c74d7856"
Parent: "bb2b010f-c453-4bee-89df-c21c861c2f74"
Template: "bb2b010f-c453-4bee-89df-c21c861c2f74"
Path: /sitecore/templates/Project/Finance/Content Types/Newsletter/Section Content/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160816T055446Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
